language: python

python:
 - 2.7
 - 3.4
 - 3.5

env:
 - DJANGO=1.8
 - DJANGO=1.9
 - DJANGO=1.10
 - DJANGO=master

matrix:
  include:
    - python: 3.6
      env: DJANGO=master
    - python: 3.5
      env: TOXENV=flake8

install:
  - pip -e git+git@github.com:Bouke/tox-travis.git@7c0468ef39bd65cd02ed864ecb6c328753c158c6#egg=tox_travis
  - pip install coveralls
script: tox
after_success: coveralls
