language: python

python:
 - 2.7
 - 3.4
 - 3.5

env:
 - DJANGO=1.8
 - DJANGO=1.9
 - DJANGO=1.10
 - DJANGO=master

matrix:
  exclude:
    - python: 3.5
      env: DJANGO=1.10
  include:
    - python: 3.5
      env: DJANGO=1.10 COVERAGE=YES
    - python: 3.6
      env: DJANGO=master
    - python: 3.5
      env: TOXENV=flake8

install: pip install tox-travis
script: tox
